cli: specify python2 in rpmbuild command
Plugsched runs with the python2 and does not depend on the default
python. See the error log:

	......
	error: attempt to use unversioned python, define %__python to
		/usr/bin/python2 or /usr/bin/python3 explicitly
	error: Macro %debuginfo_args failed to expand
	......

Signed-off-by: Erwei Deng <erwei@linux.alibaba.com>