cli: use the correct print API
Now the plugsched use the python3, so the print API should use the
"print()" instead of "print >> std.err". See the error log:

  Traceback (most recent call last):
  File "/usr/local/bin/plugsched-cli", line 36, in <module>
    print >> sys.stderr, "WARNING: YAML CLoader is not presented, it
    can be slow."
  TypeError: unsupported operand type(s) for >>:
  'builtin_function_or_method' and '_io.TextIOWrapper'. Did you mean
  "print(<message>, file=<output_stream>)"

Signed-off-by: Erwei Deng <erwei@linux.alibaba.com>